---
- name: Install unzip
  ansible.builtin.package:
    name: unzip
    state: present

- name: Create the Grafana User and Group
  block:
    - name: Create Grafana Group
      ansible.builtin.group:
        name: "{{ grafana_agent_group }}"
        gid: "{{ grafana_agent_gid }}"
        state: present
    - name: Create Grafana User
      ansible.builtin.user:
        name: "{{ grafana_agent_user }}"
        group: "{{ grafana_agent_group }}"
        uid: "{{ grafana_agent_uid }}"
        home: /var/lib/grafana-agent
        state: present

- name: Install Grafana on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  block:
    - name: Add grafana apt repository key.
      ansible.builtin.get_url:
        url: https://apt.grafana.com/gpg.key
        dest: /etc/apt/trusted.gpg.d/grafana.asc
        mode: '0644'
        force: true

    - name: Add grafana Repository
      ansible.builtin.apt_repository:
        repo: deb https://apt.grafana.com stable main
        state: present

- name: Install Grafana on Enterprise Linux
  when: ansible_os_family == "RedHat"
  block:
    - name: Add Grafana Repository
      ansible.builtin.yum_repository:
        name: grafana
        description: Grafana YUM repo
        baseurl: https://rpm.grafana.com
        gpgkey: https://rpm.grafana.com/gpg.key
        gpgcheck: true

- name: Install Grafana Package
  ansible.builtin.package:
    name: grafana-agent
    state: present

- name: Install Java Agent
  block:
    - name: Check Java Agent Version
      ansible.builtin.shell: |
        set -o pipefail
        if [ -f /var/lib/grafana-agent/jmx_prometheus_javaagent.jar ]; then
          unzip -p /var/lib/grafana-agent/jmx_prometheus_javaagent.jar META-INF/MANIFEST.MF |grep Implementation-Version | cut -d' ' -f 2
        fi
      args:
        executable: /bin/bash
      register: jmx_version_check
      changed_when: jmx_version_check.stdout != grafana_agent_jmx_version

    - name: Downloading and installing the JMX agent
      ansible.builtin.get_url:
        url: "{{ maven_url }}/{{ grafana_agent_jmx_version }}/jmx_prometheus_javaagent-{{ grafana_agent_jmx_version }}.jar"
        dest: /var/lib/grafana-agent/jmx_prometheus_javaagent.jar
        mode: '0644'
        owner: "{{ grafana_agent_user }}"
        group: "{{ grafana_agent_group }}"
      when: jmx_version_check.stdout != grafana_agent_jmx_version
    
    - name: Install the Monitoring Template
      ansible.builtin.template:
        src: "{{ grafana_agent_jmx_template }}.yaml.j2"
        dest: "/var/lib/grafana-agent/{{ grafana_agent_jmx_template }}.yaml"
        mode: '0644'
        owner: "{{ grafana_agent_user }}"
        group: "{{ grafana_agent_group }}"
    - name: Change /var/lib/grafana-agent permissions
      ansible.builtin.file:
        path: /var/lib/grafana-agent
        mode: 0775
        state: directory
  when: grafana_agent_jmx_install


- name: Create grafana-agent.yml
  ansible.builtin.template:
    src: grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml
    mode: "0644"
  notify: Restart Grafana
                            
- name: Set acls on log file directories
  block: 
    - name: Set it on the directories
      ansible.posix.acl:
        path: "{{ item }}"
        entity: "{{ grafana_agent_user }}"
        state: present
        etype: user
        permissions: rx
        recursive: true
        default: true
      with_items: "{{ grafana_agent_directory_acls }}"

    - name: Set it on existing files
      ansible.posix.acl:
        path: "{{ item }}"
        entity: "{{ grafana_agent_user }}"
        state: present
        etype: user
        permissions: rx
        recursive: true
      with_items: "{{ grafana_agent_directory_acls }}"
      tags:
        - molecule-idempotence-notest

- name: Enable and Start Grafana
  ansible.builtin.service:
    name: grafana-agent
    enabled: true
    state: started
  when: not grafana_agent_ami_builder
                            
- name: Enable Grafana Only
  ansible.builtin.service:
    name: grafana-agent
    enabled: true
  when: grafana_agent_ami_builder

#------------------------------------------------------------------------------
# Setup Grafana for AMIs
#------------------------------------------------------------------------------
- name: Setup Extra Help for Grafana on AMIs
  when: grafana_agent_ami_builder
  block:
    - name: Copy Rename Script
      ansible.builtin.copy:
        src: change_instance_name.sh
        dest: /usr/local/bin/change_instance_name.sh
        owner: root
        group: root
        mode: 0700
    - name: Copy the CloudInit entry 
      ansible.builtin.copy:
        src: 20_fix_grafana_config.cfg
        dest: /etc/cloud/cloud.cfg.d/20_fix_grafana_config.cfg
        owner: root
        group: root
        mode: 0700
